### ISSUE TITLE
Removing the soil effect based on image segmentation-Inverse

### ISSUE THREAD

**Issue by aaronszcz-USDA** [filipematias23/FIELDimageR-QGIS#2]
I created a NDVI Index. The soil is below 0. When I use fieldMask with mask crop value to 0, I am exporting only the soil values. I would like to keep the values above 0, not below. Is there a way I can inverse this? Im not sure how to invert the mask.
![fieldmask](https://github.com/filipematias23/FIELDimageR-QGIS/assets/154467478/08801c68-cc71-4c6b-aace-e196278105f4)

**Comment by filipematias23** [comment]
Hi there, thanks for asking ... We did a update in the function fieldMask(). 

If you install it again you will be able to use the crop_above check box as highlighted in the image below.

Let´s know if it worked... ok

Thanks

![image](https://github.com/filipematias23/FIELDimageR-QGIS/assets/11415688/0007566a-2d7f-4d89-90b4-d252d9815d81)

**Comment by aaronszcz-USDA** [comment]
Awesome.
It worked. Thanks!

**Comment by filipematias23** [comment]
Great...!
