### ISSUE TITLE
Thermal Images

### ISSUE THREAD

**Issue by aaronszcz-USDA** [filipematias23/FIELDimageR-QGIS#3]
Hello,
I have a single band raster, where each pixel is temperature in C.
I want to create a mask and extract field plot info, but I'm unable to use my raster as an index layer. I cannot create an index layer from it because it is not R,G,B, or multispec, its one band temperature. Also, I can't find a way to extract the mean plot info when it is single band.
Any suggestions?
Thanks!

**Comment by filipematias23** [comment]
Hi there,

Please, upload the code again ... We just did some changes for using single layers. Basically, you need to use the same TIF at MOSAIC and INDEX ... You can type any name on 'mask_layer_name'. The crop_value must be a numeric value between the layer limits ... ok.

Here is one example using DSM.tif:

![image](https://github.com/filipematias23/FIELDimageR-QGIS/assets/11415688/506b2b75-c568-4b93-b59c-4aa511bf6aaa)


Hope it helps...!

Best,
Filipe

**Comment by aaronszcz-USDA** [comment]
Perfetct, Thank you! That worked to create a masked mosaic with the single band raster.
I'm still having an issue when getting fieldinfo. I have my plot grid set up, and now I have the masked mosaic with a single band temperature, but i get this error when i run fieldinfor "Error in plotInfo[, !colnames(plotInfo) %in% c("ID"), drop = FALSE] :".
I tried to use fieldIndex to create an index of the masked mosaic, but this doesnt work with a single band raster.

Any suggestions?
Thanks!

**Comment by filipematias23** [comment]
Hi there, do you have a column called ID or plotID on your grid? Did you use the function fieldShape?

Can you share your data here for we simulate the same error and try to figure out, what’s going on?

@pspawar71, can you help us with this question?

Best,
Filipe

**Comment by filipematias23** [comment]
@aaronszcz-USDA, try uploading the function fieldInfo and test if it is working for your data now!

Please, let us know... ok

Thanks,
Filipe

**Comment by aaronszcz-USDA** [comment]
@filipematias23 
Everything worked now!!  :D 
Thanks!
Aaron

**Comment by filipematias23** [comment]
That´s great ... Check if the values make sense and if you have questions contact us... ok!
