### ISSUE TITLE
Error while using fieldSegment

### ISSUE THREAD

**Issue by Bharannn** [filipematias23/FIELDimageR-QGIS#4]
Hey,
I'm trying to use the segmentation feature of fieldSegment, however I am facing an error while running the segmentation. 

This is my ortho image, and I have created a shapefile layer with soil and plant as two classes.

![Screenshot 2023-12-26 145847](https://github.com/filipematias23/FIELDimageR-QGIS/assets/114688808/2e671815-cb56-4a88-8861-2d2670a630fd)

These are the parameters I'm giving input while running the segmentation.
![Screenshot 2023-12-26 145916](https://github.com/filipematias23/FIELDimageR-QGIS/assets/114688808/fa853910-df7c-4473-af44-0219b33b4d16)

And I am getting this error, can someone mention how to resolve this issue.
![Screenshot 2023-12-26 150025](https://github.com/filipematias23/FIELDimageR-QGIS/assets/114688808/e541fea4-41a0-4f93-a37b-5ee131260717)

**Comment by filipematias23** [comment]
Hi there,

You need to give a name to the output raster...!

![image](https://github.com/filipematias23/FIELDimageR-QGIS/assets/11415688/2d768a1b-d50b-4888-ad36-fa6c69f43dfc)

Hope it helps!

Best,
Filipe

**Comment by filipematias23** [comment]
@Bharannn,

You can also use the segmented image as the Index_Layer at the fieldMasck() function to crop the RGB image according to the selected criteria... In the example below, we cropped above 1.5 to eliminate the soil and select all plants...!

Hope it makes sense...!

Filipe

![image](https://github.com/filipematias23/FIELDimageR-QGIS/assets/11415688/1657ad55-390c-4c02-bc3d-488fd32de665)

Output:

![image](https://github.com/filipematias23/FIELDimageR-QGIS/assets/11415688/f899d8fa-38dd-4b2a-adb4-c814ac65101f)

**Comment by pspawar71** [comment]
Hey, could you please share the snapshot of the attribute table for your "train1" polygon shapefile? Also share the properties of train1 shapefile.

**Comment by pspawar71** [comment]
Hello, I replicated the tutorial image to address the issue you are encountering. It seems that you are providing an empty polygon shapefile (training sample). You may have created polygons but forgot to save it. Please save your polygon features after digitization. Let us know if this resolves the issue.  Here I am attaching the image of replicated example with similar issue.
![Screenshot (44)](https://github.com/filipematias23/FIELDimageR-QGIS/assets/83626626/dca33a78-dffa-451d-a4ba-dd0b80738f18)

**Comment by Bharannn** [comment]
Hey @filipematias23 and @pspawar71 , 
Thank you for the replies! I am able to do segmentation. I just had to add file name for the output segment in fieldSegment parameters and save the layer edits in Layer < Save Layer Edits.
